/** Generated by `supabase gen types`; do not hand edit. */
export type Json = string | number | boolean | null | { [key: string]: Json };
export type Database = { public: { Tables: Record<string, never> } };
